name: "GitHub Action for Extracting Atmos Settings"
description: "A GitHub Action for Extracting Atmos Settings from Metadata"
author: hello@cloudposse.com
branding:
  icon: "terminal"
  color: "white"
inputs:
  component:
    description: The atmos component extract the settings for.
    required: true
  stack:
    description: The atmos stack extract the settings for.
    required: true
  settings-path:
    description: The settings path using JSONPath expressions.
    required: true
outputs:
  value:
    description: "The value of the settings"
    value: ${{ steps.settings.outputs.value }}
runs:
  using: "composite"
  steps:
    - id: settings
      shell: bash
      run: |
        OUTPUT_FILE="$(tr / _ <<<${{ inputs.stack }}-${{ inputs.component }}.json)"

        # Extract the settings value from the component's stack configuration
        atmos describe component \
          ${{ inputs.component }} \
          -s ${{ inputs.stack }} \
          --format json \
          --file "$OUTPUT_FILE"
        RESULT=$?
        if [ $RESULT -ne 0 ]; then
          echo "Atmos config not found"
          exit 1
        fi
        value=$(jq -rc --arg key ${{ inputs.settings-path }} '. | getpath($key | split(".")) | if . == null then "" else . end' "$OUTPUT_FILE")
        echo "value=$value" >> $GITHUB_OUTPUT
