name: build-and-test
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  check-dist:
    name: "check-dist matches source"
    uses: cloudposse/.github/.github/workflows/shared-ci-typescript-app-check-dist.yml@main
    with:
      node-version: 20.x

  unit-test:
    name: "unit tests"
    runs-on: ubuntu-latest
    needs: check-dist
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - uses: cloudposse/github-action-setup-atmos@v2
        with:
          install-wrapper: false
      - name: run unit tests
        run: yarn test

  integration-test-single:
    name: "integration test: single setting"
    runs-on: ubuntu-latest
    needs: check-dist
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn
      - uses: cloudposse/github-action-setup-atmos@v2
        with:
          install-wrapper: false
      - uses: ./
        id: get-setting
        with:
          component: foo
          stack: core-ue1-dev
          settings-path: atmos_cli_config.components.terraform.base_path
      - uses: nick-fields/assert-action@v2
        with:
          expected: "components/terraform"
          actual: ${{ steps.get-setting.outputs.value}}

  integration-test-multiple:
    name: "integration test: multiple settings"
    runs-on: ubuntu-latest
    needs: check-dist
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn
      - uses: cloudposse/github-action-setup-atmos@v2
        with:
          install-wrapper: false
      - uses: ./
        id: get-setting
        with:
          settings: |
            - component: foo
              stack: core-ue1-dev
              settingsPath: atmos_cli_config.components.terraform.base_path
              outputPath: prop1
            - component: foo
              stack: core-ue1-dev
              settingsPath: settings.level1.level2.level3.secrets-arn
              outputPath: prop2

      - uses: nick-fields/assert-action@v2
        with:
          expected: '{"prop1":"components/terraform","prop2":"arn:aws:secretsmanager:us-east-1:000000000000:secret:MySecret-PlMes3"}'
          actual: ${{ steps.get-setting.outputs.settings}}
