name: Test atmos get setting action
on:
  #  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
  #  #
  #  # Added pull_request to register workflow from the PR.
  #  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
  #  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      base_result: ${{ steps.base.outputs.value }}
      derived_result: ${{ steps.derived.outputs.value }}
      defaults_result: ${{ steps.defaults.outputs.value }}
    steps:
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup atmos
        uses: cloudposse/github-action-setup-atmos@v1.0.0
        with:
          install-wrapper: false
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        id: base
        with:
          component: foo
          stack: core-ue1-dev
          settings-path: level1.level2.level3.secrets-arn

      - uses: ./
        id: derived
        with:
          component: derived
          stack: core-ue1-dev
          settings-path: level1.example

      - uses: ./
        id: defaults
        with:
          component: test-defaults
          stack: core-ue1-dev
          settings-path: level1.example

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: '"arn:aws:secretsmanager:us-east-1:000000000000:secret:MySecret-PlMes3"'
          actual: ${{ needs.test.outputs.base_result }}

      - uses: nick-fields/assert-action@v1
        with:
          expected: '"result"'
          actual: ${{ needs.test.outputs.derived_result }}

      - uses: nick-fields/assert-action@v1
        with:
          expected: '"result"'
          actual: ${{ needs.test.outputs.defaults_result }}
